#!/usr/bin/python

import re, sys

# Usage: python repl_vcell.py < input.v
origLib = sys.stdin.read()

for suffix in ["_X1", "_X2", "_X4"]:
    print "// Autogenerated set with suffix " + suffix
    print re.sub(r"module (.*?)\(", r"module \1" + suffix + r"(", origLib)

