#!/usr/bin/python3

# $lic$
# Copyright (C) 2019-2024 by Daniel Sanchez
#
# This file is part of the Minispec compiler and toolset.
#
# Minispec is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, version 2.
#
# Minispec is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.

import re, sys

# Usage: python3 repl_vcell.py < input.v
origLib = sys.stdin.read()
for suffix in ["_X1", "_X2", "_X4"]:
    print("// Autogenerated set with suffix " + suffix)
    print(re.sub(r"module (.*?)\(", r"module \1" + suffix + r"(", origLib))
